scanners:
    deviantart:
        watchlist:
            key: deviantart:watchlist
            url: http://www.deviantart.com/notifications/#view=deviations
    apod:
        watchlist: false
    #furaffinity:
    #    watchlist:
    #        key: furaffinity:watchlist
    #        url: http://www.furaffinity.net/msg/submissions/
    blogspot:
        watchlist: false
        domains:
            - www.equestriadaily.com
            - equestriadaily.com
    livejournal:
        watchlist: false
    wordpress:
        watchlist: false
    tumblr:
        watchlist: false
    derpibooru:
        watchlist: false
    steamcommunity:
        watchlist: false
    weasyl:
        watchlist:
            key: weasyl:watchlist
            url: https://www.weasyl.com/messages/submissions
    inkbunny:
        watchlist: false
#    pixiv:
#        watchlist: false
